language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

install:
    - composer self-update
    - composer install --prefer-dist --dev -o
    - composer require squizlabs/php_codesniffer:2.*

script:
  - phpunit
  - ./vendor/bin/phpcs -p --standard=PSR2 ./src ./tests

notifications:
  email: false
